import { getServerSession } from "next-auth/next"
import { redirect, notFound } from "next/navigation"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { authOptions } from "@/lib/auth"
import prisma from "@/lib/prisma"
import { ApplicationStatusBadge } from "@/components/application-status-badge"
import { hasRnRPermission } from "@/lib/roles"
import { ApplicationReviewActions } from "@/components/application-review-actions"
import { formatRoleDisplay } from "@/lib/roles"

export default async function ApplicationDetailPage({ params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions)

  if (!session?.user) {
    redirect("/auth/signin")
  }

  // Check if user has RNR permissions
  if (!hasRnRPermission(session.user.role as string)) {
    redirect("/applications")
  }

  const applicationId = Number.parseInt(params.id)

  if (isNaN(applicationId)) {
    notFound()
  }

  // Get application with all related data
  const application = await prisma.application.findUnique({
    where: { id: applicationId },
    include: {
      user: true,
      template: true,
      reviewer: true,
      responses: {
        include: {
          question: true,
        },
        orderBy: {
          question: {
            order: "asc",
          },
        },
      },
      notes: {
        include: {
          author: true,
        },
        orderBy: {
          createdAt: "desc",
        },
      },
    },
  })

  if (!application) {
    notFound()
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Application Details</h1>
          <p className="text-muted-foreground">
            {application.user.name} - {application.template.name}
          </p>
        </div>
        <Link href="/rnr/applications">
          <Button variant="outline">Back to Applications</Button>
        </Link>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2">
          <Card>
            <CardHeader>
              <CardTitle>Application Responses</CardTitle>
              <CardDescription>Submitted on {new Date(application.createdAt).toLocaleString()}</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                {application.responses.map((response) => (
                  <div key={response.id} className="space-y-2">
                    <h3 className="font-medium">{response.question.questionText}</h3>
                    <div className="p-3 bg-muted rounded-md whitespace-pre-wrap">
                      {response.response || <span className="text-muted-foreground italic">No response provided</span>}
                    </div>
                    {response.flaggedAsAI && (
                      <p className="text-sm text-amber-600">This response may have been generated by AI</p>
                    )}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Applicant Information</CardTitle>
            </CardHeader>
            <CardContent>
              <dl className="space-y-4">
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Name</dt>
                  <dd>{application.user.name}</dd>
                </div>
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Email</dt>
                  <dd>{application.user.email}</dd>
                </div>
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Role</dt>
                  <dd>{formatRoleDisplay(application.user.role)}</dd>
                </div>
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Discord ID</dt>
                  <dd>{application.user.discordId || "Not linked"}</dd>
                </div>
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Joined</dt>
                  <dd>{new Date(application.user.createdAt).toLocaleDateString()}</dd>
                </div>
              </dl>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Application Status</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <div className="text-sm font-medium text-muted-foreground mb-1">Current Status</div>
                  <ApplicationStatusBadge status={application.status} interviewStatus={application.interviewStatus} />
                </div>
                <div>
                  <div className="text-sm font-medium text-muted-foreground mb-1">Reviewer</div>
                  <div>{application.reviewer?.name || "Unassigned"}</div>
                </div>
                {application.denialCount > 0 && (
                  <div>
                    <div className="text-sm font-medium text-muted-foreground mb-1">Previous Denials</div>
                    <div>{application.denialCount}</div>
                  </div>
                )}
                {application.cooldownUntil && (
                  <div>
                    <div className="text-sm font-medium text-muted-foreground mb-1">Cooldown Until</div>
                    <div>{new Date(application.cooldownUntil).toLocaleString()}</div>
                  </div>
                )}
                {application.interviewCompletedAt && (
                  <div>
                    <div className="text-sm font-medium text-muted-foreground mb-1">Interview Completed</div>
                    <div>{new Date(application.interviewCompletedAt).toLocaleString()}</div>
                  </div>
                )}
                {application.interviewFailedAt && (
                  <div>
                    <div className="text-sm font-medium text-muted-foreground mb-1">Interview Failed</div>
                    <div>{new Date(application.interviewFailedAt).toLocaleString()}</div>
                  </div>
                )}
              </div>

              <div className="mt-6">
                <ApplicationReviewActions application={application} />
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Notes & History</CardTitle>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="notes">
            <TabsList>
              <TabsTrigger value="notes">Notes ({application.notes.length})</TabsTrigger>
              <TabsTrigger value="history">Application History</TabsTrigger>
            </TabsList>
            <TabsContent value="notes" className="pt-4">
              {application.notes.length > 0 ? (
                <div className="space-y-4">
                  {application.notes.map((note) => (
                    <div key={note.id} className="p-4 border rounded-md">
                      <div className="flex justify-between items-start mb-2">
                        <div className="font-medium">{note.author.name}</div>
                        <div className="text-sm text-muted-foreground">{new Date(note.createdAt).toLocaleString()}</div>
                      </div>
                      <div className="whitespace-pre-wrap">{note.content}</div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-muted-foreground">No notes have been added to this application.</p>
              )}
            </TabsContent>
            <TabsContent value="history" className="pt-4">
              <div className="space-y-4">
                <div className="p-4 border rounded-md">
                  <div className="flex justify-between items-start mb-2">
                    <div className="font-medium">Application Created</div>
                    <div className="text-sm text-muted-foreground">
                      {new Date(application.createdAt).toLocaleString()}
                    </div>
                  </div>
                  <div>
                    {application.user.name} submitted an application for {application.template.name}
                  </div>
                </div>
                {application.status !== "PENDING" && (
                  <div className="p-4 border rounded-md">
                    <div className="flex justify-between items-start mb-2">
                      <div className="font-medium">
                        Application {application.status === "ACCEPTED" ? "Accepted" : "Denied"}
                      </div>
                      <div className="text-sm text-muted-foreground">
                        {new Date(application.updatedAt).toLocaleString()}
                      </div>
                    </div>
                    <div>
                      {application.reviewer?.name || "A reviewer"}{" "}
                      {application.status === "ACCEPTED" ? "accepted" : "denied"} this application
                    </div>
                  </div>
                )}
                {application.interviewStatus === "INTERVIEW_COMPLETED" && (
                  <div className="p-4 border rounded-md">
                    <div className="flex justify-between items-start mb-2">
                      <div className="font-medium">Interview Completed</div>
                      <div className="text-sm text-muted-foreground">
                        {new Date(application.interviewCompletedAt!).toLocaleString()}
                      </div>
                    </div>
                    <div>{application.reviewer?.name || "A reviewer"} marked the interview as completed</div>
                  </div>
                )}
                {application.interviewStatus === "INTERVIEW_FAILED" && (
                  <div className="p-4 border rounded-md">
                    <div className="flex justify-between items-start mb-2">
                      <div className="font-medium">Interview Failed</div>
                      <div className="text-sm text-muted-foreground">
                        {new Date(application.interviewFailedAt!).toLocaleString()}
                      </div>
                    </div>
                    <div>{application.reviewer?.name || "A reviewer"} marked the interview as failed</div>
                  </div>
                )}
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  )
}
